// This client mirrors the autogenerated client but adds safe fallbacks
// Do NOT edit the autogenerated client.ts. Import from this file in the UI instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { PUBLIC_ENV } from '@/lib/env';

export const supabase = createClient<Database>(
  PUBLIC_ENV.SUPABASE_URL,
  PUBLIC_ENV.SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
